FROM node:22-alpine

WORKDIR /app

RUN npm install -g npm@latest

COPY package.json ./


RUN npm install --omit=dev --no-audit --no-fund

USER node
COPY dist ./dist
COPY prisma.config.ts ./
COPY prisma ./prisma

RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/serve.js"]