FROM node:20-alpine

WORKDIR /app

# habilita npm moderno (evita bugs)
RUN npm install -g npm@latest

# copia apenas manifests primeiro (cache bom)
COPY package.json ./

# instala dependências de produção
RUN npm install --omit=dev --no-audit --no-fund

# copia código necessário
COPY dist ./dist
COPY prisma ./prisma

# gera Prisma Client dentro do container
RUN npx prisma generate
