FROM node:22-alpine

WORKDIR /app

RUN npm install -g npm@latest

COPY package.json ./


RUN npm install --omit=dev --no-audit --no-fund

USER node
COPY dist ./dist
COPY prisma.config.ts ./
COPY prisma ./prisma
RUN mkdir -p /app/certs
COPY global-bundle.pem /app/certs/global-bundle.pem
COPY alloy /app/alloy

RUN npx prisma generate