name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Subir containers (já rodam testes)
        working-directory: app/backend
        run: |
          docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit