name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Criar .env
        working-directory: app/backend
        run: |
          {
            echo "POSTGRES_USER=admin"
            echo "POSTGRES_PASSWORD=loremiptsu"
            echo "POSTGRES_DB=test"
            echo "MODE=development"
            echo "DATABASE_URL="
            echo "BUCKET_NAME=marketst1"
            echo "REDIS_PASSWORD=loremi"
            echo "ACCESS_TOKEN=qiwje39493849qweqwenqjdb3//123"
            echo "REFRESH_TOKEN=loremiptsu123134h"
            echo "NODE_ENV=development"
            echo "REDIS_URL="
            echo "ORIGIN_KEY=http://localhost:5173"
            echo "PORT=8080"
            echo 'PRIVATE_KEY={"project_id":"mockado"}'
          } > .env

      - name: Subir containers (já rodam testes)
        working-directory: app/backend
        run: docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit --exit-code-from test